spring.application.name=courseflow
spring.datasource.url=jdbc:postgresql://sdmay26-19.ece.iastate.edu:5432/Test
spring.datasource.username=postgres
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=org.postgresql.Driver
# --- JPA / HIBERNATE CONFIG ---
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true